version: 1.0.{build}
image: Visual Studio 2017

build_script:
 - cd hello_world_application
 - cmake -H. -Bbuild
 - cmake --build build --target hello_world
 - cd ..
 - cd solver_application
 - cmake -H. -Bbuild
 - cmake --build build --target solver
notifications:
- provider: Email
  to:
  - serafinkosty@gmail.com
  subject: TP lab04
  message: Successfully finished build
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
