name: CMake




on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]




env:

  BUILD_TYPE: Release




jobs:

  build:

    runs-on: ubuntu-latest




    steps:

    - uses: actions/checkout@v3

    

    - name: Create and build formatter_lib

      working-directory: formatter_lib

      run: cmake -H. -Bbuild
      
    - name: build formatter_lib

      working-directory: formatter_lib

      run: cmake --build build  

    

    - name: Create and build formatter_ex_lib

      working-directory: formatter_ex_lib

      run: cmake -H. -Bbuild
      
    - name: build formatter_ex_lib

      working-directory: formatter_ex_lib

      run: cmake --build build

    

    - name: Create and build hello_world_application

      working-directory: hello_world_application

      run: cmake -H. -Bbuild
      
    - name: build hello_world_application

      working-directory: hello_world_application

      run: cmake --build build

    

    - name: Create and build solver_lib

      working-directory: solver_lib

      run: cmake -H. -Bbuild
      
    - name: build solver_lib

      working-directory: solver_lib

      run: cmake --build build

    

    - name: Create and build solver_application

      working-directory: solver_application

      run: cmake -H. -Bbuild
      
    - name: Create and build solver_application

      working-directory: solver_application

      run: cmake --build build
